replicaCount: 2

image:
  repository: ghcr.io/cdesplanches-orka/microservice-b/ms-b
  tag: "latest"

serviceA:
  url: "http://microservice-a:80"
  grpcAddress: "microservice-a:50051"

service:
  port: 80
  targetPort: 3001
