version: '3.8'

services:
  microservice-a:
    image: ghcr.io/cdesplanches-orka/microservice-a/ms-a:latest
    ports:
      - "3000:3000"
      - "50051:50051"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GRPC_PORT=50051
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  microservice-b:
    image: ghcr.io/cdesplanches-orka/microservice-b/ms-b:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SERVICE_A_URL=http://microservice-a:3000
      - SERVICE_A_GRPC=microservice-a:50051
    depends_on:
      microservice-a:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
