apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "microservice-b.fullname" . | quote } }
  labels:
    app: { { include "microservice-b.name" . | quote } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { include "microservice-b.name" . | quote } }
  template:
    metadata:
      labels:
        app: { { include "microservice-b.name" . | quote } }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/health"
        prometheus.io/port: { { .Values.service.targetPort | quote } }
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: microservice-b
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: { { .Values.service.targetPort } }
          env:
            - name: SERVICE_A_URL
              value: "{{ .Values.serviceA.url }}"
            - name: SERVICE_A_GRPC
              value: "{{ .Values.serviceA.grpcAddress }}"
          readinessProbe:
            httpGet:
              path: /health
              port: { { .Values.service.targetPort } }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: { { .Values.service.targetPort } }
            initialDelaySeconds: 10
            periodSeconds: 10
