apiVersion: v1
kind: Service
metadata:
  name: "{{ include "microservice-b.fullname" . }}"
  labels:
    app: "{{ include "microservice-b.name" . }}"
spec:
  selector:
    app: "{{ include "microservice-b.name" . }}"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
